In [6]:
import numpy
a = numpy.arange(12)
b = numpy.reshape(a, (3, 4))  #a번
print(b)
a = numpy.reshape(b, 12)  #b번
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
